version: "2.0"
services:
  nginx-vod:
    build:
      context: nginx-vod/.
    ports:
      - "8080:80"
    volumes:
      - ./nginx-vod/videos/:/opt/static/videos/
  go-file-api:
    build:
      context: go-file-api/.
    ports:
      - "8090:80"
    volumes:
      - ./nginx-vod/videos/:/opt/static/videos/
  ng-home-vod:
    build:
      context: ng-home-vod/.
    ports:
      - "80:80"
